### ISSUE TITLE
Introduction to NB5

### ISSUE THREAD

**Issue by fmaussion** [ehultee/CdeC-glaciologia#20]
The illustration of glacier changes "since 1970" is outdated (2003), in particular the thickening of Norwegian glaciers due to a special NAO decade is not actual anymore, and the "Karakoram Anomaly" is not visible. However, the figure best illustrates your point ("¿por qué algunos glaciares responden con mayor fuerza que otros al mismo cambio climático?"). After quite some searching I haven't found such a compelling graphic. 

However, I would still suggest to replace the figure with these two:

![img](https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2019/04/global_glacier_mass_loss_1961_2016/19340812-1-eng-GB/Global_glacier_mass_loss_1961_2016_large.jpg) 
([source](https://www.esa.int/Our_Activities/Observing_the_Earth/Glaciers_lose_nine_trillion_tonnes_of_ice_in_half_a_century))

and:

![img](https://glacierhub.org/wp-content/uploads/2017/02/ngeo2863-f1.jpg) 
([source](https://glacierhub.org/2017/02/21/research-confirms-significance-climate-change-glacier-retreat/))

What do you think? I can happily do the changes

**Comment by ehultee** [comment]
Yes, this is good.  Other options would be something more local, like Alaska tidewater glacier front comparisons (which are weird because of the TW cycle, but show that nearby glaciers can behave differently) or glaciers on different faces of the same nevado (windward/leeward precip effects).  But we can think about this later.  These graphics are good!
